ngram-size = 1

[[sample]]
input = "Yes"
label = "yes"

[[sample]]
input = "Yeah"
label = "yes"

[[sample]]
input = "Yep"
label = "yes"

[[sample]]
input = "Yup"
label = "yes"

[[sample]]
input = "Yea"
label = "yes"

[[sample]]
input = "Sure"
label = "yes"

[[sample]]
input = "Absolutely"
label = "yes"

[[sample]]
input = "Definitely"
label = "yes"

[[sample]]
input = "Of course"
label = "yes"

[[sample]]
input = "For sure"
label = "yes"

[[sample]]
input = "Indeed"
label = "yes"

[[sample]]
input = "Affirmative"
label = "yes"

[[sample]]
input = "Roger"
label = "yes"

[[sample]]
input = "Totally"
label = "yes"

[[sample]]
input = "Certainly"
label = "yes"

[[sample]]
input = "Without a doubt"
label = "yes"

[[sample]]
input = "You bet"
label = "yes"

[[sample]]
input = "Uh-huh"
label = "yes"

[[sample]]
input = "Right on"
label = "yes"

[[sample]]
input = "Cool"
label = "yes"

[[sample]]
input = "Okie dokie"
label = "yes"

[[sample]]
input = "Aye"
label = "yes"

[[sample]]
input = "Yass"
label = "yes"

[[sample]]
input = "Fo sho"
label = "yes"

[[sample]]
input = "Bet"
label = "yes"

[[sample]]
input = "10-4"
label = "yes"

[[sample]]
input = "No"
label = "no"

[[sample]]
input = "Nope"
label = "no"

[[sample]]
input = "Nah"
label = "no"

[[sample]]
input = "Nuh-uh"
label = "no"

[[sample]]
input = "No way"
label = "no"

[[sample]]
input = "Not at all"
label = "no"

[[sample]]
input = "no"
label = "no"

[[sample]]
input = "Not really"
label = "no"

[[sample]]
input = "I don't think so"
label = "no"

[[sample]]
input = "Absolutely not"
label = "no"

[[sample]]
input = "No chance"
label = "no"

[[sample]]
input = "No way, José"
label = "no"

[[sample]]
input = "Out of the question"
label = "no"

[[sample]]
input = "By no means"
label = "no"

[[sample]]
input = "Under no circumstances"
label = "no"

[[sample]]
input = "Never"
label = "no"

[[sample]]
input = "Not in a million years"
label = "no"

[[sample]]
input = "Not happening"
label = "no"

[[sample]]
input = "No can do"
label = "no"

[[sample]]
input = "Not on your life"
label = "no"

[[sample]]
input = "Hell no"
label = "no"

[[sample]]
input = "Nah fam"
label = "no"

[[sample]]
input = "Pass"
label = "no"

[[sample]]
input = "Hard pass"
label = "no"

[[sample]]
input = "Nopey dopey"
label = "no"

[[sample]]
input = "Nix"
label = "no"
